### ISSUE TITLE
Aggregate multiple publications from Kotlin multiplatform targets and multi gradle submodules

### ISSUE THREAD

**Issue by rjaros** [GradleUp/nmcp#1]
I have a KMP project with a dozen of gradle submodules. Every module defines at least three publications (common, js, wasm). It would be nice to aggregate all these publications (about 50) to a single zip, uploaded to Central Portal as a single deployment.

**Comment by martinbonnin** [comment]
Fixed with https://github.com/GradleUp/nmcp/commit/e1bcc9f801c17b888a84416135d4f395dc2aa130
