### ISSUE TITLE
Publishing workflow based on gradle's maven-publish

### ISSUE THREAD

**Issue by solonovamax** [GradleUp/nmcp#17]
Hi,

I'd like to propose a publishing workflow that's a bit more based on gradle's own built-in `maven-publish`.

I've implemented such a thing here myself: https://github.com/solo-studios/nyx/tree/master/src/main/kotlin/ca/solostudios/nyx/sonatype
note specifically:
- `SonatypePublishPlugin.kt`
- `PublishToSonatypeMavenRepository.kt`
- `SonatypeMavenRemotePublisher.kt`

these classed are primarily copied directly from gradle's own interal code. do be warned, they do also use internal gradle apis.

some advantages of this approach are:
- you interract with it in the exact same way as the normal `maven-publish` plugin.
- the task structure is exactly the same
- fully compatible with any existing plugins that use the existing `maven-publish` plugin

just thought I'd put this here as smth to consider.

**Comment by martinbonnin** [comment]
Thanks for opening this. 

At this time though there are no plans to add features or change the API. Feel free to fork the plugin if needed or users can use the code above as a reference but I'm marking this closed as there's nothing really actionable to be done here.

**Comment by solonovamax** [comment]
> Thanks for opening this. 
> 
> At this time though there are no plans to add features or change the API. Feel free to fork the plugin if needed or users can use the code above as a reference but I'm marking this closed as there's nothing really actionable to be done here. 

yeah no worries, just wanted to suggest it as it may have been desireable.

but, I already publish that plugin myself so I won't fork this plugin to add it.
